server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

spring:
  application:
    name: service-web
  cloud:
    loadbalancer:
      retry:
        enabled: false